version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: hogariq-prod-db
    restart: always
    environment:
      POSTGRES_USER: hogariq_user
      POSTGRES_PASSWORD: hogariq_prod_password_9988
      POSTGRES_DB: hogariq_prod_db
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hogariq-prod-redis
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: hogariq-prod-ollama
    restart: always
    volumes:
      - ollama_prod_data:/root/.ollama

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hogariq-prod-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://hogariq_user:hogariq_prod_password_9988@db:5432/hogariq_prod_db?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: hogariq_prod_secret_key_change_me_in_coolify
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: llama3.2:1b
      PORT: 3000
    depends_on:
      - db
      - redis
      - ollama

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: hogariq-prod-web
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      PORT: 3000
    depends_on:
      - backend

volumes:
  postgres_prod_data:
  ollama_prod_data:
